import{a as q,S as B,i as n}from"./assets/vendor-D2TjyBWE.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const E="https://pixabay.com/api/",R="49651039-b61b5892bf5245ff30c976637";async function m(s,r){const t={key:R,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15};try{return(await q.get(E,{params:t})).data}catch(i){throw console.error("❌ Error fetching data from Pixabay:",i),i}}const g=document.querySelector(".gallery"),p=document.querySelector(".loader"),y=document.querySelector(".load-more"),$=new B(".gallery a",{captionsData:"alt",captionDelay:250});function b(s){const r=s.map(({webformatURL:t,largeImageURL:i,tags:e,likes:o,views:a,comments:v,downloads:S})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${i}">
          <img class="gallery-image" src="${t}" alt="${e}" />
        </a>
        <div class="gallery-info">
          <p><b>Likes:</b> ${o}</p>
          <p><b>Views:</b> ${a}</p>
          <p><b>Comments:</b> ${v}</p>
          <p><b>Downloads:</b> ${S}</p>
        </div>
      </li>
    `).join("");g.insertAdjacentHTML("beforeend",r),$.refresh()}function M(){g.innerHTML=""}function L(){p.classList.remove("is-hidden")}function c(){p.classList.add("is-hidden")}function w(){y.classList.remove("is-hidden")}function l(){y.classList.add("is-hidden")}const h=document.querySelector(".form"),P=document.querySelector(".load-more");let d=1,u="",f=0;h.addEventListener("submit",async s=>{s.preventDefault();const r=h.elements.searchQuery.value.trim();if(!r){n.warning({message:"Enter something to search!",position:"topRight"});return}u=r,d=1,M(),l(),L();try{const t=await m(u,d);if(f=t.totalHits,t.hits.length===0){n.info({message:"No images found. Try again.",position:"topRight"}),c();return}b(t.hits),c(),f>15&&w(),t.hits.length<15&&(l(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{n.error({message:"Something went wrong...",position:"topRight"}),c()}});P.addEventListener("click",async()=>{d+=1,L(),l();try{const s=await m(u,d);b(s.hits),c(),document.querySelectorAll(".gallery-item").length>=f?(l(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):w();const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}catch{n.error({message:"Something went wrong...",position:"topRight"}),c()}});
//# sourceMappingURL=index.js.map
